### PR TITLE
argon2: detect allocation failures in `hash_password_into`

### LINKED ISSUE #566: `Argon2::hash_password_into` should use fallible memory allocations
`Argon2::hash_password_into` crashes on 32-bit architectures when using the FIRST RECOMMENDED parameter option (see [Section 4 of RFC 9106](https://www.rfc-editor.org/rfc/rfc9106.html#name-parameter-choice)) because it tries to infallibly allocate the 2 GiB buffer.

We believe that the straight-forward, easy-to-use interfaces should be safe by default.  Following that, `Argon2::hash_password_into` should make a fallible allocation, returning allocation errors instead of crashing.

### PR DESCRIPTION
**Pull request by newpavlov**
Closes #566

### CODE REVIEW

File: argon2/src/error.rs [hunk 1]
```diff
@@ -116,6 +120,7 @@ impl From<Error> for password_hash::Error {
             Error::ThreadsTooMany => InvalidValue::TooLong.param_error(),
             Error::TimeTooSmall => InvalidValue::TooShort.param_error(),
             Error::VersionInvalid => password_hash::Error::Version,
+            Error::AllocFail => InvalidValue::TooLong.param_error(),
```
Comment (newpavlov) [inline argon2/src/error.rs:123]: I am not sure what to do here. Maybe we should add a new error variant to `password_hash::Error`?

File: argon2/src/block.rs [hunk 2]
```diff
@@ -154,3 +154,43 @@ impl Zeroize for Block {
...
+
+#[cfg(feature = "alloc")]
+impl Blocks {
+    pub fn new(len: usize) -> Option<Self> {
+        use alloc::alloc::{Layout, alloc_zeroed};
+        use core::ptr::NonNull;
+
+        let layout = Layout::array::<Block>(len).ok()?;
+        // SAFETY: e use `alloc_zeroed` correctly
+        let p = unsafe { alloc_zeroed(layout) };
```
Comment (jonasmalacofilho) [inline argon2/src/block.rs:173]: This depends on the caller (which, to be fair, is limited to this crate) not passing `len == 0`.

Wouldn't it be better to explicitly assert that `layout.size() > 0`?

File: argon2/src/error.rs [hunk 3]
```diff
@@ -56,8 +56,11 @@ pub enum Error {
     /// Time cost is too small.
     TimeTooSmall,
 
-    /// Invalid version
+    /// Invalid version.
     VersionInvalid,
+
+    /// Failed to allocate memory.
+    AllocFail,
```
Comment (jonasmalacofilho) [inline argon2/src/error.rs:63]: Note: this is a semver bump, as the enum is public and exhaustive.

**Review by jonasmalacofilho — COMMENTED** [review]
Note that my allocation-only benchmark in #566 suggests this _could_ be a tiny bit slower than `vec![Block::default, ...]`.

So maybe it would be good to benchmark this with high-ish memory sizes, or at least with the 19 MiB and 46 MiB sizes recommended by OWASP?

File: argon2/src/block.rs (hunk 2 above)
Comment (newpavlov) [reply argon2/src/block.rs:173]: Ah, indeed. `alloc_zeroed` requires for `Layout` to be non-zero. We probably can simply return `None` in such case instead of using a dangling pointer on zero length.

**Comment by tarcieri** [comment]
Maybe we should try to land #547 first so we can gauge any impact on performance?

File: argon2/src/error.rs (hunk 1 above)
Comment (tarcieri) [reply argon2/src/error.rs:123]: Sure

File: argon2/src/block.rs [hunk 4]
```diff
@@ -154,3 +154,47 @@ impl Zeroize for Block {
...
+    pub fn new(len: usize) -> Option<Self> {
+        use alloc::alloc::{Layout, alloc_zeroed};
+        use core::ptr::NonNull;
+
+        if len == 0 {
+            return None;
+        }
+        
+        let layout = Layout::array::<Block>(len).ok()?;
+        // SAFETY: e use `alloc_zeroed` correctly
```
Comment (tarcieri) [inline argon2/src/block.rs:176]: I'm not sure what this is trying to say?

File: argon2/src/error.rs [hunk 5]
```diff
@@ -79,6 +82,7 @@ impl fmt::Display for Error {
             Error::ThreadsTooMany => "too many threads",
             Error::TimeTooSmall => "time cost is too small",
             Error::VersionInvalid => "invalid version",
+            Error::AllocFail => "allocation failure",
```
Comment (tarcieri) [inline argon2/src/error.rs:85]: Perhaps `OutOfMemory`?

File: argon2/src/block.rs (hunk 4 above)
Comment (newpavlov) [reply argon2/src/block.rs]: Fixed.

**Comment by newpavlov** [comment]
>Maybe we should try to land https://github.com/RustCrypto/password-hashes/pull/547 first so we can gauge any impact on performance?

I think we should merge this PR, then #547 without the alignment workaround, and then finally add the alignment workaround to `Blocks` in a separate PR. I am still not 100% convinced that we should add the workaround. It needs additional investigation in my opinion.

**Review by tarcieri — APPROVED** [review]
